### PR TITLE
Fixed #3

### LINKED ISSUE #3: pcl_librealsense_viewer crashes with "--list" switch.
```
nhu@nhu-z87:~/devel2/robotics/pcl/builddir$ ./bin/pcl_librealsense_viewer --list
Viewer for LibRealSense devices (run with --help for more information)
Connected devices: 
  #1  2411003672
terminate called after throwing an instance of 'rs::error'
  what():  cannot stop device without first starting device
Aborted (core dumped)

```

### PR DESCRIPTION
**Pull request by lebronzhang**
@huningxin 
please take a look:)

### CODE REVIEW

File: io/src/librealsense/librealsense_device_manager.cpp [hunk 1]
```diff
@@ -120,7 +119,7 @@ void
 pcl::io::librealsense::LibRealSenseDeviceManager::releaseDevice (const std::string& sn)
 {
   boost::mutex::scoped_lock lock (mutex_);
-  pcl::io::librealsense::LibRealSenseDeviceManager::stopDevice (sn);
+  if (!thread_close_flag_[sn]) pcl::io::librealsense::LibRealSenseDeviceManager::stopDevice (sn);
```
Comment (huningxin) [inline io/src/librealsense/librealsense_device_manager.cpp]: I am curious why `releaseDevice` needs to call `stopDevice`?

File: io/src/librealsense/librealsense_device_manager.cpp [hunk 2]
```diff
@@ -51,7 +51,6 @@ pcl::io::librealsense::LibRealSenseDeviceManager::LibRealSenseDeviceManager ()
 
 pcl::io::librealsense::LibRealSenseDeviceManager::~LibRealSenseDeviceManager ()
 {
-  context_.~context();
```
Comment (huningxin) [inline io/src/librealsense/librealsense_device_manager.cpp:54]: Yes. No need to call destructor explicitly.

File: visualization/tools/librealsense_viewer.cpp [hunk 3]
```diff
@@ -98,16 +115,6 @@ class LibRealSenseViewer
     LibRealSenseViewer (pcl::LibRealSenseGrabber& grabber)
     : grabber_ (grabber)
     , viewer_ ("LibRealSense Viewer")
-    , grabber_second_ (grabber)
```
Comment (huningxin) [inline visualization/tools/librealsense_viewer.cpp:101]: This code is for multiple grabber test? Why remove them?

File: io/src/librealsense/librealsense_device_manager.cpp (hunk 1 above)
Comment (lebronzhang) [inline io/src/librealsense/librealsense_device_manager.cpp]: I think releaseDevice means deviceManager give up the control of the giving device, so it is necessary to check if the device is running and stop the device in case the other grabber want to use this device again.

Comment (huningxin) [inline io/src/librealsense/librealsense_device_manager.cpp]: However, the only caller of the `releaseDevice` is the `LibRealSenseGrabberImpl::~LibRealSenseGrabberImpl` where it calls `stop` first.

The underlying librealsense doesn't provide the `release` method, what's the purpose of the `LibRealSenseDeviceManager::releaseDevice`? Only to remove the mapping?

File: visualization/tools/librealsense_viewer.cpp (hunk 3 above)
Comment (lebronzhang) [inline visualization/tools/librealsense_viewer.cpp:101]: Yeah, it is for multiple grabber test. Because I suppose that the viewer is just an example of using librealsense grabber, and one grabber is enough. Besides, I checked the other grabber's viewer, they use only one grabber, I think it is better to keep in line with them.

**Comment by huningxin** [comment]
Another suggestion, please use one commit to fix one issue. And ideally, one PR with one commit. With that, it is easier to separate review and merge. Please follow that. Thanks!

File: io/src/librealsense/librealsense_device_manager.cpp (hunk 1 above)
Comment (lebronzhang) [inline io/src/librealsense/librealsense_device_manager.cpp]: Yeah, you are right, I forgot to check this, it is unnecessary to stop again in the  `LibRealSenseDeviceManager`,  I will remove stop in the `LibRealSenseDeviceManager`.

The purpose of `LibRealSenseDeviceManager::releaseDevice` is indeed just to remove the mapping, but the purpose of the map is to check if the device is captured, if the device is already in the map, the other grabber cannot use this device.

**Comment by huningxin** [comment]
So simply, we need to create three PRs, one for option, one for remove unused code and another one for  fix crash issue. And please add "fix #number" into your commit log to associate to corresponding issue (See https://help.github.com/articles/closing-issues-via-commit-messages/)

File: visualization/tools/librealsense_viewer.cpp (hunk 3 above)
Comment (huningxin) [inline visualization/tools/librealsense_viewer.cpp:101]: That makes sense. Let's focus this sample only for one grabber case. BTW, does your grabber implementation supports multiple grabbers for one camera device?

File: io/src/librealsense/librealsense_device_manager.cpp (hunk 1 above)
Comment (huningxin) [inline io/src/librealsense/librealsense_device_manager.cpp]: Right. Please do that. Thanks.

File: visualization/tools/librealsense_viewer.cpp (hunk 3 above)
Comment (lebronzhang) [inline visualization/tools/librealsense_viewer.cpp:101]: No, one grabber correspond with only one device, if the others want to use the same data from one captured device, they have to register themselves to the same grabber. :)

**Comment by lebronzhang** [comment]
Thank you for your suggestion @huningxin , I will do it right now:)

**Comment by huningxin** [comment]
@lebronzhang , the peer review process is: one sends PR, let another (reviewer) review, reviewer gives "LGTM" (looks good to me) then merge it.

**Comment by lebronzhang** [comment]
@huningxin Sorry and thank you for your explaination, I will follow this process since now, and should I take some actions to mitigate the impact of my error, like revert the merge or something else?

**Comment by huningxin** [comment]
No worries. Let's follow the process from now on.
